- hosts: all
  tasks:
     - name: stop container.
       shell: docker container stop mycardsite
     - name: remove container
       shell: docker container rm mycardsite
     - name: create container
       shell: docker container run -itd --name mycardsite -p 80:80 959597/mysite
